[JD] chats upd

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,6 @@
-npm run lint && npm run format
+if (npm run lint && npm run format && git add .); then
+  echo "Pre-commit checks passed!"
+else
+  echo "Pre-commit checks failed!"
+  exit 1
+fi
